### ISSUE TITLE
Consider Maven central release

### ISSUE THREAD

**Issue by cheshire** [ultimate-pa/smtinterpol#15]
Hi,

Would you consider releasing SMTInterpol to Maven Central? (http://search.maven.org/)
It's a most commonly used repository of Java projects, much like pypi for Python, or Debian repositories for Linux.
It doesn't require using Maven, and can be done from ANT.
Projects released to Maven central can be used in other Java projects by essentially adding one configuration line.
I can help with technical issues related to Maven Central release.

Regards,
George

**Comment by jhoenicke** [comment]
Hi, 
just an update.  We will consider Maven support but we haven't commited to it, yet.  I have to talk to our Maven expert when we is back :)

**Comment by cheshire** [comment]
@jhoenicke Hi, I think I have had a dinner with the said Maven expert yesterday :P 
In short, I am not suggesting moving to Maven (which is _completely_ orthogonal),
but simply adding a target to ANT to push to Maven central.
I have a fork of smtinterpol with this patch, and I would send a pull request shortly.
To do the releases you just need to register at https://issues.sonatype.org/ and to register your PGP key for the email used for the sonatype account.

**Comment by PhilippWendler** [comment]
I would like to suggest that if this is done, to handle the dependencies of SMTInterpol differently.
Strictly speaking, this is independent from Maven Central, but it becomes more relevant for JARs published there.

Now both log4j and java-cup are included in the SMTInterpol JAR. This is nice for using it as an application, but not so nice for using it as a library, because it can lead to a dependency hell where multiple conflicting versions of the same class are on the class path.
Thus I propose to remove log4j from the JAR and instead declare it as a dependency in the Maven metadata, and for java-cup (because AFAIK it is a modified version of java-cup, right?) to include it in the JAR but with renamed classes. There exist tools for the latter, it is typically named "shading". Example (I haven't used it): https://github.com/shevek/jarjar

The existing JAR file can of course still be provided for other users.

We currently experience the problem with conflicting versions of java-cup in CPAchecker and we have a workaround based on loading SMTInterpol in its own classloader, but it would be nice if we could drop that workaround.

**Comment by jhoenicke** [comment]
We got rid of the log4j dependency (Jürgen had a branch in the queue that I merged now).  With java-cup I still have to decide on it.  Yes, we use our own custom version of javacup, that has some new features that we heavily rely on. Probably I move the package name to `com.github.jhoenicke.javacup`.  I don't like the java_cup package name anyway.

**Comment by PhilippWendler** [comment]
Thanks, that would be great.
