### ISSUE TITLE
Simple file sends SMTInterpol into a loop

### ISSUE THREAD

**Issue by agacek** [ultimate-pa/smtinterpol#17]
SMTInterpol seems to loop on this file:

  https://gist.github.com/agacek/53390b2a37de3d6ea2e8

Other solvers (z3, yices, yices 2, mathsat) solve it instantly (oddly cvc4 also loops on it). The file has a defined function in it. If the function is inlined then SMTInterpol solves the problem instantly. I thought defined functions were always just inlined by the SMT solver anyway?

**Comment by jhoenicke** [comment]
The loop is in the explanation of a found conflict. SMTInterpol found that the current decisions lead to an unsatisfiability and is trying to build an explanation to find the wrong decision.  The infinite loop should not be possible here; I will investigate it. 

I get the same loop when inlining the T function.  Note that small differences (e.g. different names for the variables, different order of the assertions) may lead to a different order in trying to solve the formula which can affect whether this bug is triggered.

**Comment by jhoenicke** [comment]
I finally found time to look into this.  The problem is not an infinite loop, but that the explanation dag for the composite reasons corresponds to an exponentially large tree.  We currently do a simple tree iteration through the dag to collect the contributing guards.  Fix is not easy; it would require to traverse the explanations with a dag-aware algorithm.  It also requires some rewrite of the whole explain logic.

**Comment by jhoenicke** [comment]
I guess this can be closed.  Some changes in the simple (when the new SOI pivoter was added) prevent these deep nested explanations.
