### ISSUE TITLE
Escaping for reserved variable names

### ISSUE THREAD

**Issue by cheshire** [ultimate-pa/smtinterpol#20]
Hi All,

Creating a variable called `select`, or `store`, or `true` fails with SMTInterpol, with an error message "Function X already defined".
While it's true that this function is indeed already defined for arrays, I think the proper course of action is to apply an escaping mechanism with "|" symbols, which is already found in SMTInterpol.

All other solvers we have tested (Z3, Princess, Mathsat5) do apply such escaping themselves.

**Comment by jhoenicke** [comment]
I assume you refer to defineFun/declareFun.  You can actually create variables named `select` and it works (but may produce invalid smt2 scripts when using the `LoggingScript`).  The Script interface that we propose makes it impossible to have different functions/constants with the same name.  The reason is that we only reference function symbols by their name.  You create a function symbol and later you access it by giving the same name as first argument to `term`.  It is impossible to know whether the string `"select"` as argument for term refers to the internal function symbol or the user defined function symbol.

If you want to avoid this problem in your application, you can prefix every user defined symbol by a fixed unique prefix, e.g. `_`. 

BTW, the SMT2 standard says that `|select|` and `select` are the same symbol.  In the Java interface the function names should be given without the `|` characters and when writing the names to a script file the `|` quotes are added when necessary.

**Comment by cheshire** [comment]
> BTW, the SMT2 standard says that |select| and select are the same symbol

Yes, however Z3/Princess/Mathsat5 all treat them differently when using their API (I assume they apply escaping themselves). Maybe they are mapped to the same constant when SMT-LIB input is used.

Of course we can do escaping on our end, but I thought it would make more sense inside SMTInterpol, e.g. inside `Script#declareFun`. OK we'll have to do it on our end then.

**Comment by cheshire** [comment]
@jhoenicke Actually when creating variables with "|" symbols in them using SMTInterpol API, something funny happens: SMTInterpol happily accepts them, considers them to be different to variables without pipes, and crashes with assertion error in `quoteIdentifier` method on printing models or serialization.
Is the lack of pipe symbols a precondition on `defineFun`/`declareFun`? Shouldn't in this case those functions fail with assertion errors, it's a bit bizarre when everything goes well until you try to serialize the context?

**Comment by jhoenicke** [comment]
I will probably add an assertion to `defineFun`/`declareFun`/`variable`/`declareSort`/...; have to discuss this with my collegues.  The `\` symbol has the same problem. 

As I said, working around the first problem in SMTInterpol Script interface is not possible as the `term` function is used for both user-defined functions and theory-defined functions with a simple string as function symbol.

**Comment by PhilippWendler** [comment]
Any update on this? We just found a bug in our code where an assertion that `declareFun` does not allow `|` in the name would have been helpful :-)

**Comment by jhoenicke** [comment]
The extra check for \ and | is now implemented in 7032d22234079da583c9c3aea9d91e8004c7a5ab.

As explained above, we cannot automatically quote reserved symbols.
