### ISSUE TITLE
Minimum/maximum value that satisfies?

### ISSUE THREAD

**Issue by io7m** [ultimate-pa/smtinterpol#36]
Hello.

Apologies if this isn't an appropriate place to ask, but I've not been able to find anywhere else to ask questions.

Is it possible to get the solver to optimize for a minimum and/or maximum value when trying to satisfy a problem?

Take the following trivial example:

```
(set-option :produce-assignments true)
(set-option :produce-proofs true)

(set-logic QF_LIA)

(declare-fun p () Int)

(assert (>= p 0))
(assert (<= p 23))

(check-sat)

(get-value (p))
```

If I run that locally here, the value of `p` is `0`. That's obviously acceptable given the assertions I specified, but what if I want `p` to be the highest value it can be (`23` in this case)?

I'm looking to use SMTInterpol to model version constraints in a software package system with statements like `package p depends on package q version >= 1 <= 3` and would obviously prefer if the solver picked the largest values for all assignments that it could.

**Comment by jhoenicke** [comment]
There is no direct support for this in SMTInterpol.  You can try to work around this, by refining your query, e.g. after you get sat and a model, add the assertion that p should be strictly larger than its current value and iterate until you get unsat.  To accelerate it, ask if p can be larger than its current value plus some large offset that you half when you get unsat (use push and pop to add temporary assertions).

If your problem is linear and convex and your optimizing function is linear there may be more efficient tools for this.  Look for linear programming solver.

**Comment by io7m** [comment]
Thank you. I think a linear programming solver might be the better way to handle this.
